apiVersion: batch/v1
kind: Job
metadata:
  name: tt
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: tt
        image: vivekkar/test:testjob
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - ls
      restartPolicy: Never